version: '3'

networks:
  proxy:
    external:
      name: ${NETWORK_PROXY}

services:
  proxy:
    image: traefik
    command: --docker
    hostname: ${DOMAIN_TRAEFIK}
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "5001:443" 
      - "5002:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${PWD}/traefik/acme.json:/acme.json
