version: '3'

networks:
  proxy:
    external:
      name: ${NETWORK_PROXY}
  gitlab-net:

volumes:
  data:
  log:
  config:

services:
  proxy:
    image: traefik
    command: --docker
    hostname: ${DOMAIN_TRAEFIK}
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "5001:443" 
      - "5002:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${PWD}/traefik/acme.json:/acme.json

  gitlab:
    image: gitlab/gitlab-ce
    hostname: ${DOMAIN_GITLAB}
    environment:
      VIRTUAL_HOST: ${DOMAIN_GITLAB}
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${DOMAIN_GITLAB}'
        gitlab_rails['gitlab_shell_ssh_port'] = 2332
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "mail.${DOMAIN}"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "gitlab@${DOMAIN}"
        gitlab_rails['smtp_password'] = "${PASS_SMTP}"
        gitlab_rails['smtp_domain'] = "${DOMAIN}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['gitlab_email_from'] = 'gitlab@${DOMAIN}'
        gitlab_rails['gitlab_email_reply_to'] = 'gitlab@${DOMAIN}'
    networks:
      proxy:
      gitlab-net:
        aliases:
          - ${DOMAIN_GITLAB}
    ports:
      - "2332:22"
    volumes:
      - config:/etc/gitlab
      - log:/var/log/gitlab
      - data:/var/opt/gitlab

    labels:
      traefik.enable: 'true'
      traefik.docker.network: '${NETWORK_PROXY}'
      traefik.backend: 'gitlab'
      traefik.frontend.rule: 'Host:${DOMAIN_GITLAB}'
      traefik.default.protocol: 'http'
      traefik.port: '80'

  gitlab-runner:
    image: gitlab/gitlab-runner
    networks:
      - gitlab-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/runner:/etc/gitlab-runner
