debug = false
logLevel = "ERROR"

InsecureSkipVerify = true
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        certFile = "/certs/gitlab.domain.crt"
        keyFile = "/certs/gitlab.domain.key"

[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$jw2RVpnA$EDRAtiwa/KT6tMoSQIYKv0"]

[docker]
domain = "domain"
endpoint = "unix://var/run/docker.sock"
watch = true

[retry]
